#!/usr/bin/env bash
# Detect LAN IP and write env files for phone + Expo Go development.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

detect_ip() {
  if command -v ipconfig >/dev/null 2>&1; then
    # macOS — Wi-Fi usually en0
    local ip
    ip="$(ipconfig getifaddr en0 2>/dev/null || true)"
    if [[ -n "$ip" ]]; then echo "$ip"; return; fi
    ip="$(ipconfig getifaddr en1 2>/dev/null || true)"
    if [[ -n "$ip" ]]; then echo "$ip"; return; fi
  fi
  if command -v ip >/dev/null 2>&1; then
    ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1); exit}'
    return
  fi
  hostname -I 2>/dev/null | awk '{print $1}'
}

LAN_IP="${LAN_IP:-$(detect_ip)}"
if [[ -z "$LAN_IP" || "$LAN_IP" == 127.* ]]; then
  echo "❌ לא הצלחתי לזהות IP ברשת. הגדר ידנית:"
  echo "   export LAN_IP=192.168.x.x"
  echo "   ./scripts/setup-phone-dev.sh"
  exit 1
fi

API_URL="http://${LAN_IP}:8000"
WEB_URL="http://${LAN_IP}:5173"

# Root .env
if [[ ! -f .env ]]; then
  cp .env.example .env
  echo "✓ נוצר .env מהדוגמה"
fi

# Mobile Expo
cat > mobile/.env <<EOF
# Auto-generated by setup-phone-dev.sh — IP: $LAN_IP
EXPO_PUBLIC_API_URL=$API_URL
EOF

# Frontend — direct API for phone browser (bypasses Vite proxy)
cat > frontend/.env.local <<EOF
# Auto-generated — for npm run dev:phone
VITE_API_URL=$API_URL
EOF

echo ""
echo "=== Levera — מוכן לטלפון ==="
echo ""
echo "  IP ברשת:     $LAN_IP"
echo "  Backend:     $API_URL"
echo "  Web (PWA):   $WEB_URL"
echo ""
echo "  mobile/.env ו-frontend/.env.local עודכנו."
echo ""
echo "הרץ ב-3 טרמינלים:"
echo ""
echo "  # 1 — MongoDB (אם יש Docker)"
echo "  docker compose up -d"
echo ""
echo "  # 2 — Backend"
echo "  cd backend && pip install -r requirements.txt && python3 run_api.py"
echo ""
echo "  # 3 — Web (אופציונלי, PWA)"
echo "  cd frontend && npm install && npm run dev:phone"
echo ""
echo "  # 4 — Expo (React Native)"
echo "  cd mobile && npm install && npm start"
echo ""
echo "בדיקה מהטלפון (דפדפן): $API_URL/health"
echo "Expo Go: סרוק QR — ודא שאותה Wi-Fi!"
echo ""
